spring:
  application:
    name: springboot-kafka-consumer
  kafka:
    # 消费者配置
    consumer:
      # 默认消费者组
      group-id: consumeSingle
      # 自动提交 offset 默认 true
      enable-auto-commit: false
      # 当kafka中没有初始offset或offset超出范围时将自动重置offset
      # earliest:重置为分区中最小的offset
      # latest:重置为分区中最新的offset(消费分区中新产生的数据)
      # none:只要有一个分区不存在已提交的offset,就抛出异常
      auto-offset-reset: latest
      # 集群地址
      bootstrap-servers: localhost:9093
---
spring:
  profiles: p1
server:
  port: 6071