liteflow:
  rule-source: flows/*.xml
  #------以下非必须-------
  #slot的数量，默认值为1024
  slot-size: 2048
  #异步线程最长的等待时间秒(只用于when)，默认值为15
  when-max-wait-second: 20
  monitor:
    #是否开启监控log打印，默认值为false
    enable-log: true
    #监控队列存储大小，默认值为200
    queue-limit: 300
    #监控一开始延迟多少执行，默认值为300000毫秒，也就是5分钟
    delay: 10000
    #监控日志打印每过多少时间执行一次，默认值为300000毫秒，也就是5分钟
    period: 10000